//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registor.SQL_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Уволенные = new HashSet<Уволенные>();
        }
    
        public int КодСотрудника { get; set; }
        public string ФИО { get; set; }
        public bool Статус { get; set; }
        public int КодСПА { get; set; }
        public int КодДолжности { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual СПА СПА { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Уволенные> Уволенные { get; set; }
    }
}
